### ISSUE TITLE
What is the status of the port

### ISSUE THREAD

**Issue by kolbis** [Elders/Hystrix.NET#2]
Hi
I would like to know the status of this port.
Can it be used for production environment? 
How ready is it?
what are the plans for it?

BR

**Comment by sdluxeon** [comment]
Hey,
We are using this in production for several months now, and we don't have any issues with it. It's fully compatible with Netflix Dashboards(including Turbine) so feel free to use it. We also have a hostable nuget with the dasboard https://github.com/Elders/Hystrix.NET.Dashboard . We also support a Servo.NET implementation  with https://github.com/Elders/Servo.NET and https://github.com/Elders/Servo.NET.Atlas 
Since we also have the develop features on other projects there is little time for documentaion, but if you invest time going trough the code and figure how it works, you could benefit a lot. If you intend using any of the projects here https://github.com/Elders we will support you and hopefully fill out the documentation.
Pull requests are always welcome :)

**Comment by kolbis** [comment]
Thanks!

1. Where can I find some code examples?
2. I would like to integrate it with RabbitMQ.  Any suggestions here?

Thanks.

**Comment by mynkow** [comment]
here is an example where you can play with different settings. https://github.com/Elders/Hystrix.NET/tree/master/src/Elders.Hystrix.NET.Example

Can you please elaborate on the integration with rabbitmq?

**Comment by kolbis** [comment]
Yes. We are doing microservices with RabbitMQ and masstransit.
http://masstransit-project.com/ 

I would like to add a middleware which will be executed before we send any Message to RabbitMQ.
http://masstransit.readthedocs.io/en/master/middleware/index.html

The middleware will execute Hystrix command and will utilize the circuit breaker + dashboard.

**Comment by mynkow** [comment]
we do exactly the same but not with mass transit. We use [Cronus](https://github.com/Elders/Cronus). Here is our middleware which integrates Cronus and Hystrix => https://github.com/Elders/Cronus.Hystrix

We also use RabbitMQ => https://github.com/Elders/Cronus.Transport.RabbitMQ

**Comment by kolbis** [comment]
Thanks.
I am trying to setup a test which uses Hystix.
Here is the test:
![image](https://cloud.githubusercontent.com/assets/13493085/20675923/a883e85c-b596-11e6-8463-7a638e16f3ad.png)

Here is the Command:
![image](https://cloud.githubusercontent.com/assets/13493085/20675957/c42dc154-b596-11e6-89b2-0bc9a93b15ad.png)

Here is the command setter factory:
![image](https://cloud.githubusercontent.com/assets/13493085/20675971/d0c0da78-b596-11e6-8511-889d3888c570.png)

Now, I am trying to simulate the circuit breaker.
I am unable to see it working.
1. Can you please explain the different options for HystrixCOmmandProperiesSetter?
e.g. WithExecutionIsolationThreadTimeout, WithExecutionIsolationStrategy, WithExecutionIsolationThreadInterruptOnTimeout, and etc..
2. how would you configure it to fail fast?

BR,

Guy

**Comment by mynkow** [comment]
You should first take a look at the [defaults](https://github.com/Elders/Hystrix.NET/blob/0b78dd833f116bf1c84f05cab3397bd81e26024c/src/Elders.Hystrix.NET/Strategy/Properties/Default/HystrixPropertiesCommandDefault.cs)

Then every command which you create can have different configuration based on the needs. Please go through the defaults first to get more context and then we will come up with reasonable configuration for you. Please also specify what do you expects such as number of failed requests in what time frame. How long the CB should be opened, etc OR **describe a business case which is best for configuring Hystrix**

**Comment by kolbis** [comment]
Thanks!
I got it working. I will share some of the code later on.
Next is to see the dashboard.
Any recommendations?

**Comment by kolbis** [comment]
Hi --
Regarding the dashboard:
1. how do you publish streams from a service so that the dashboard will pick it up?
2. how do you configure the dashboard? (I assume we need to create a web site and install the dashboard nugget). can you please provide some more information?
BR

**Comment by mynkow** [comment]
I did quick setup guide => https://github.com/Elders/Hystrix.NET.Dashboard

Please ping back if it works for you

**Comment by kolbis** [comment]
Thanks!
I will give it a try.

One more question regarding HystixCommand which should run async using Task.
For example:
![image](https://cloud.githubusercontent.com/assets/13493085/20794327/66775724-b7d4-11e6-8640-b7b3c1cafb4b.png)

The issue I am having with the above implementation is that I cannot trip the circuit (open it).
1. how would you implement it?
2. is there a way to indicate to the HystixCommand that the run method failed without throwing exception?

**Comment by kolbis** [comment]
Regarding the dashboard.
I have successfully integrated the stream. I can see it in the browser:
![image](https://cloud.githubusercontent.com/assets/13493085/20795246/cae72550-b7d8-11e6-96d6-2e31f0a6ff55.png)

I have issue with the dashboard.
I have followed the instruction for the dashboard BUT I think we are missing something.
I saw that the staticFiles are embedded resources.
How do I browse to the actual dashboard?

**Comment by sdluxeon** [comment]
https://github.com/Elders/Hystrix.NET.Dashboard
If you followed everything you should be able to see it at http://localhost:9000/dashboard
And you will have to pass the stream url (localhost:10900/Tester) to the dashboard

**Comment by sdluxeon** [comment]
https://cloud.githubusercontent.com/assets/13493085/20794327/66775724-b7d4-11e6-8640-b7b3c1cafb4b.png
Regarding your question:
1. Seems like a good starting point for a base class, but usually for every command you have different configurations, like if you make a query by id you'd expect that this operation is fast and the configured timeout will be like 500 ms, but if you are calling a heavy query over multiple tables etc you would like this timeout to be longer. So exect that you will have a lot of small devianions from the base class. As of right now i don't see any reason for it as its just a wrapper.
2. Nope you can't and it does not makes sense to have another way to notify the faliure. Your system could have different error strategies based on the execptions. In some cases you would want an exponential backoff in other cases an immediate retry would makes sense. For error handling you could see what the guyes from umbraco did, its a good abstraction with a lot of extension points -> https://github.com/dylansu/umbraco/tree/49355255917370ae82b6fd8e3324a41f2a39fc77/src/Umbraco.Core/Persistence/FaultHandling

**Comment by kolbis** [comment]
Regarding dashboard, works great! Thanks.
Just love those metrics :)
Good job guys.

Some performance questions:
1. Have you tested the performance when using hystrix in various configurations?
2. Have you tested the performance and network usage when using the streams? (We have ~150 different microservices. each one on a normal day runs 8 instances)

**Comment by kolbis** [comment]
Some more question about setting up turbine.
If I have s instances running the same service. they both need to report the stream.
I need to see them both aggregated in the turbine.
1. So, what would be the address they will report to?
2. what would be the address I will put in the dashboard?
3. how do I define custom cluster? 

BR

**Comment by mynkow** [comment]
@Sinstraliz configured for us Turbine. @Sinstraliz can you please create a guide for this?

**Comment by mynkow** [comment]
@kolbis I am closing this issue. Please create a separate issues for every topic to track this better. You can link the new issues with this one for context.
